export const resumeStringsEn = {
  title: "Résumé",
  home: "Home",
  print: "Print",
  description:
    "Click on any section or lines to hide information before printing.",
  technologies: "Technologies and languages",
  education: "Education",
  workExperience: "Work experience",
  projects: "Projects",
  interests: "Interests",
  academicLife: "Academic life",
  gpa: "GPA",
  average: "Average",
  extension: "Extension",
  organizations: "Organizations",
  events: "Events",
  speeches: "Speeches",
  competitions: "Competitions",
  publications: "Publications",
  fullVersion: "Full version at",
};
