export const resumeStringsPt = {
  title: "Currículo",
  home: "Início",
  print: "Imprimir",
  description: "Clique em qualquer seção ou linha para ocultar informações antes de imprimir.",
  technologies: "Tecnologias e linguagens",
  education: "Educação",
  workExperience: "Experiência profissional",
  projects: "Projetos",
  interests: "Interesses",
  academicLife: "Vida acadêmica",
  gpa: "Média ponderada",
  average: "Média",
  extension: "Extensão",
  organizations: "Organizações",
  events: "Eventos",
  speeches: "Palestras",
  competitions: "Competições",
  publications: "Publicações",
  fullVersion: "Versão completa em",
};
